[package]
name = "actix-base"
version = "0.1.0"
edition = "2021"

[lib]
name = "actix_base"
path = "src/lib.rs"

# Dependencies
[dependencies]
actix-web = "4.*"
serde = { version = ">=1.0.0", features = ["derive"] }
serde_json = ">=1.0.0"
